# Generated by Django 5.1.3 on 2024-12-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
