# Generated by Django 5.1.3 on 2024-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='faculty',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='مهندسی کامپیوتر', max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
