# Generated by Django 5.1.3 on 2024-12-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_duration',
            field=models.FloatField(verbose_name='Exam Duration (hours)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='first_day_duration',
            field=models.FloatField(verbose_name='First Day Duration (hours)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_day_duration',
            field=models.FloatField(verbose_name='Second Day Duration (hours)'),
        ),
    ]
