# Generated by Django 5.1.3 on 2025-01-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='professor',
            new_name='professor_id',
        ),
    ]
